# Generated by Django 5.0.1 on 2024-03-29 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_blogcomment_author_blog_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Write your full name here', max_length=30),
            preserve_default=False,
        ),
    ]
