# Generated by Django 5.0.1 on 2024-03-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blogcomment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=25)),
                ('logo', models.ImageField(upload_to='images/Companylogo')),
                ('welcome_message', models.TextField()),
                ('contact', models.IntegerField()),
                ('whatsapp', models.IntegerField()),
                ('facebook', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('who_we_are', models.TextField()),
                ('how_we_help', models.TextField()),
                ('about_us', models.TextField()),
                ('disclaimer', models.TextField()),
                ('address_image', models.ImageField(upload_to='images/addressImage')),
                ('copyright', models.CharField(max_length=50)),
            ],
        ),
    ]
