# Generated by Django 5.0.1 on 2024-03-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_companydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='facebook',
            field=models.CharField(max_length=35),
        ),
    ]
