# Generated by Django 5.0.1 on 2024-03-30 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_companydetails_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='full_disclaimer',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
