# Generated by Django 5.0.1 on 2024-03-30 03:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_companydetails_full_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='shopping_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='facebook',
            field=models.URLField(max_length=35),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='whatsapp',
            field=models.URLField(),
        ),
    ]
