# Generated by Django 5.0.1 on 2024-03-30 03:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_companydetails_shopping_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='embedded_video_source',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
