# Generated by Django 5.0.1 on 2024-03-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_companydetails_nav_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='facebook',
            field=models.URLField(),
        ),
    ]
