# Generated by Django 5.0.1 on 2024-03-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_category_mini_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['post_date']},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['comment_date']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['post_date']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['contact_date']},
        ),
    ]
