# Generated by Django 5.0.1 on 2024-03-30 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_blog_options_alter_blogcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='post_date',
            field=models.DateField(default=datetime.date.fromtimestamp),
        ),
    ]
