# Generated by Django 5.0.1 on 2024-03-30 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_category_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='post_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
